from __future__ import annotations

import csv
import json
from pathlib import Path

import pytest
from PIL import Image
from pptx import Presentation
from pptx.util import Inches, Pt

from scripts.common import sha256_file


def _set_font(text_frame, name: str = "Microsoft YaHei") -> None:
    for paragraph in text_frame.paragraphs:
        for run in paragraph.runs:
            run.font.name = name
            run.font.size = Pt(18)


def _add_text(slide, text: str, left: float, top: float, width: float, height: float) -> None:
    shape = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    shape.text_frame.text = text
    _set_font(shape.text_frame)


def make_deck(path: Path, image_path: Path, *, bad: bool = False) -> None:
    presentation = Presentation()
    presentation.slide_width = Inches(13.333333)
    presentation.slide_height = Inches(7.5)
    blank = presentation.slide_layouts[6]
    cover = presentation.slides.add_slide(blank)
    _add_text(cover, "Evidence-First PPT 测试文件", 1.0, 2.8, 11.0, 0.7)

    for slide_number in range(2, 4 if bad else 3):
        slide = presentation.slides.add_slide(blank)
        phrase = "阅读要点：" if bad and slide_number == 2 else "核心结论："
        body = (
            f"{phrase}真实科研素材必须先核验项目归属、变量、时间、区域和单位。\n"
            "第一，使用官方机构或同行评议论文原图；第二，保持坐标轴与图例完整；\n"
            "第三，图片等比显示且裁剪值为零；第四，每页保留可追溯的页脚来源。"
        )
        _add_text(slide, "科研素材完整性与证据链", 0.8, 0.5, 11.7, 0.6)
        _add_text(slide, body, 0.8, 1.4, 6.0, 3.5)
        picture = slide.shapes.add_picture(str(image_path), Inches(7.2), Inches(1.5), width=Inches(5.0))
        if bad and slide_number == 2:
            picture.crop_right = 0.1
        _add_text(slide, "图源：测试项目自有无版权图，2026。", 7.2, 5.35, 5.0, 0.35)
        _add_text(slide, f"{slide_number:02d}", 6.4666665, 7.05, 0.4, 0.25)
    presentation.save(path)


def make_config(path: Path, slide_count: int, *, page_numbers: bool = True) -> None:
    config = {
        "$schema": "../../schemas/project_config.schema.json",
        "schema_version": "1.0.0",
        "workflow_version": "1.0.0",
        "project": {"id": "test-001", "name": "test", "type": "course", "language": "zh-CN"},
        "scope": {"allowed_files": [], "forbidden_files": []},
        "presentation": {
            "expected_slide_count": slide_count,
            "aspect_ratio": "16:9",
            "allowed_fonts": ["Microsoft YaHei"],
            "cover_slides": [1],
            "directory_slides": [],
            "transition_slides": [],
            "page_number": {"required": page_numbers, "start_slide": 2, "center_tolerance_inches": 0.08},
            "banned_phrases": ["阅读要点", "课堂解读", "课程示意"]
        },
        "qa": {
            "fail_on_out_of_bounds": True,
            "fail_on_text_overlap": True,
            "fail_on_nonzero_picture_crop": True,
            "fail_on_duplicate_evidence_media": True,
            "fail_on_banned_phrase": True,
            "fail_on_explicit_disallowed_font": True,
            "fail_on_unmapped_evidence_media": False,
            "fail_on_low_density": False,
            "ignore_template_media_repeated_on_fraction": 0.8,
            "text_overlap_smaller_area_fraction": 0.08,
            "minimum_body_characters_without_visual": 180,
            "minimum_body_characters_with_visual": 80,
            "minimum_substantive_units": 4,
            "low_density_exempt_slides": [1],
            "crop_exempt_slides": [],
            "overlap_exempt_slides": []
        }
    }
    path.write_text(json.dumps(config, ensure_ascii=False, indent=2), encoding="utf-8")


def make_metadata(path: Path, filename: str, digest: str, *, valid: bool = True) -> None:
    fields = [
        "asset_id", "filename", "case_name", "ppt_page", "figure_title", "source_type",
        "source_organization", "source_title", "publication_year", "figure_number", "page_number",
        "doi", "source_url", "download_url", "license_or_usage_note", "verification_status", "file_sha256"
    ]
    row = {
        "asset_id": "asset-001",
        "filename": filename,
        "case_name": "QA test",
        "ppt_page": "2",
        "figure_title": "自有无版权测试图",
        "source_type": "project-owned",
        "source_organization": "Evidence-First PPT Workflow",
        "source_title": "Automated test asset",
        "publication_year": "2026",
        "figure_number": "1",
        "page_number": "",
        "doi": "",
        "source_url": "https://example.com/evidence",
        "download_url": "https://example.com/evidence.png",
        "license_or_usage_note": "Generated by the test suite and safe to redistribute.",
        "verification_status": "verified" if valid else "unverified",
        "file_sha256": digest,
    }
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerow(row)


@pytest.fixture
def sample_project(tmp_path: Path) -> dict[str, Path]:
    asset_root = tmp_path / "assets"
    asset_root.mkdir()
    image_path = asset_root / "test_evidence.png"
    Image.new("RGB", (1200, 800), "#2F6B4F").save(image_path)
    deck_path = tmp_path / "good.pptx"
    config_path = tmp_path / "config.json"
    metadata_path = asset_root / "source_metadata.csv"
    make_deck(deck_path, image_path)
    make_config(config_path, 2)
    make_metadata(metadata_path, image_path.name, sha256_file(image_path))
    return {
        "root": tmp_path,
        "asset_root": asset_root,
        "image": image_path,
        "deck": deck_path,
        "config": config_path,
        "metadata": metadata_path,
    }
